server:
  port: 9000


jwt:
  # 임의의 Base64 인코딩된 비밀키 (실무에선 더 복잡하게 만들어서 숨겨야 함)
  secret: V2hhdGlzVGhlTW9zdEltcG9ydGFudFRoaW5nSW5MaWZlSXRoaW5rSXIsSGVhbHRoQW5kSGFwcGluZXNz
  # 토큰 유효 시간 (30분 = 1000 * 60 * 30 밀리초)
  expiration: 1800000

spring:
  application:
    name: FairTicket

  datasource:
    url: jdbc:mysql://localhost:3306/fairticket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root        # 본인 ID (보통 root)
    password: 1234        # ⭐ 본인 비밀번호로 변경 필수!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create    # ⭐ 실행 시 테이블 자동 생성 (나중엔 update나 validate로 변경)
    properties:
      hibernate:
        format_sql: true  # 쿼리 예쁘게 출력
        show_sql: true    # 콘솔에 쿼리 출력
    open-in-view: false

  # Redis 설정 (나중에 쓸 거 미리 세팅)
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug